language: node_js
node_js:
- '5'
addons:
  code_climate:
    repo_token: "6851e38436e965235aad1ccaa9dc8b3301300c0fbcf258a6e900c483a509397d"
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: Lk6AE2vUgnnd00gWoYIqZgJNu7UqvlFZjm8M44W1fbCfsLbT6ICowBgaj7V9LEpVzONOvMGOsMT4oCIw5ZeNy4fQq7y3PVkmGxH/ckBx0Naz56rSqVRbXDwx2jp75G934b57rHutuy1a+66Le5uxgowKe1G0jkT8OXYj5tHxVPdqjovUy/mp+hwKPai0pXFTE8IYYE2qsjzoSzylZCZelcSe5H6fay001NGHGff1C1OatldRY44PWolNU+hRHwh/bYXb57vwQmfVSJJRrfeNIgtRniaiVFe4Qqhf7nK3i/z9N2ako/NVEgpycCGJP40UWWAlYgUp3mG/u8WWxX0t0pa6L4Yay1cStuHlAP05uMLhtjHzHWZscWPvZ7KWs16dG0MkpBkNBzUHjXf7RqZvFJFmhSMfMvVv44DpyRmklSOq72mGlKR3WskPnprYSpyoFPOY2u99ShwtFFIPCWZS1wU3eZT0loWLt6t7/csO69hjL0YzcG7BDURlSQLycsiSs6+iz3lUUQ2lRZXBxf/1PZB5DdRLKwmOM88tvK5p+vfZkRClsvWsec1kDbstZJaBewDbNu3rdGPHXqzd9Bnw12v50IpS9NRhIhrjwIQ/bASwMkTLWTn8KE3/FQemmgu/CWZaAI6+lT0CCZGGtacnG2njuGYP/eO1kRxuXkXx7QQ=
  on:
    tags: true
    branches: true
after_success:
- bash <(curl -s https://codecov.io/bash)
branches:
  only:
  - "/^v[0-9]/"
